CREATE TABLE curso (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255),
    categoria_id ENUM('APERFEICOAMENTO','CAPACITACAO','OFICINA','TREINAMENTO') NOT NULL,
    data_criacao DATETIME,
    status ENUM('ATIVO', 'INATIVO', 'CONCLUIDO') NOT NULL
);